# -*- coding: utf-8 -*-
"""zomato dayta analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJAIkpbFXaxli7XCg0bOWcG44vsH8KTf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
dataframe = pd.read_csv("/content/Zomato data .csv")
print(dataframe)

from google.colab import drive
drive.mount('/content/drive')

print(dataframe.head())

def handelrate(value):
  value = str(value).split('/')
  value = value[0]
  return float(value)
dataframe['rate'] = dataframe['rate'].apply(handelrate)
print(dataframe.head())

dataframe.info()



"""type of resturat where customer order more"""

sns.countplot(x=dataframe['listed_in(type)'])
plt.xlabel('type of restaurant')

"""**conclusion : most of the people like dinning type

votes to each type of resturant
"""

grouped_data = dataframe.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes': grouped_data})
plt.plot(result,c="green",marker="o")
plt.xlabel('type of restaurant',c="red",size=20)
plt.ylabel('votes',c="red",size=20)

dataframe.head()

"""rating that majority of customers give"""

plt.hist(dataframe['rate'],bins=5)
plt.xlabel('rating')
plt.show()

"""majority of rewaturant receives 3.5 to 4.0 rating

average spending of couples online food order
"""

dataframe.head()

couple_order = dataframe['approx_cost(for two people)']
sns.countplot(x=couple_order)

"""5.  which mode receive maximum rfating"""

plt.figure(figsize=(6,6))
sns.boxplot(y='rate',x='online_order',data=dataframe)
plt.show()

"""which resturant receive more offline orders"""

pivot_table = dataframe.pivot_table(index='listed_in(type)',columns='online_order',values='votes',aggfunc='size',fill_value=0)
sns.heatmap(pivot_table,annot=True,cmap="YlGnBu",fmt='d')
plt.title("heatmaps")
plt.xlabel("online_order")
plt.ylabel("listed_in(type)")
plt.show()